name: EnchantedSteak
version: '${project.version}'
main: com.ashkiano.enchantedsteak.EnchantedSteak
api-version: '1.16'
author: AshKiano
description: Adds enchanted steak which gives player Haste effect.